name: square_in_app_payments_example
description: Demonstrates how to use the square_in_app_payments plugin.

version: 1.1.0+1

environment:
  sdk: ">=2.0.0-dev.68.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  http: ^0.12.0
  uuid: ^2.0.0
  pana: ^0.13.9+1
  built_value: ^7.0.0
  built_collection: ^4.0.0
  meta: ^1.1.6
  cloud_firestore: ^0.13.0+1
  firebase_auth: ^0.15.3
  google_sign_in: ^4.0.4
  apple_sign_in: ^0.1.0
  cupertino_icons: ^0.1.2
  intl: 0.15.7
  date_range_picker: ^1.0.5
  auto_size_text: ^2.0.2
  flutter_spinkit: ^3.1.0
  flutter_auth_buttons: ^0.5.0
  firebase_storage: ^3.1.5
  font_awesome_flutter: ^8.5.0
  image_picker: 0.6.3+4
  shared_preferences: ^0.4.0
  photo_view: ^0.9.2
  #image_gallery_saver: ^1.2.1
  matrix_gesture_detector: ^0.1.0
  #flutter_email_sender: ^3.0.1
  permission_handler: ^5.0.0+hotfix.6
  provider: ^4.1.2
  device_info: ^0.4.1+4
  google_fonts: ^0.3.2
  flutter_credit_card: ^0.1.3
  progress_dialog: ^1.2.3

dev_dependencies:
  square_in_app_payments:
    path: ../

flutter:
  uses-material-design: true

  assets:
    - assets/
